version: '3.8'

services:
  app:
    tty: true
    restart: always
    container_name: bomi_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'

    environment:
      DB_ADDRESS: 172.31.43.90:3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      SECRET_KEY: ${SECRET_KEY}
      MY_KEY: ${MY_KEY}
      MY_SALT: ${MY_SALT}

volumes:
  mysql_data: