spring:
  application:
    name: main

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ADDRESS}/bomi?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  security:
    jwt:
      secret: ${SECRET_KEY}
      access-expiration: 604800000
      refresh-expiration: 2592000000
      encryption: ${MY_KEY}
      salt: ${MY_SALT}

server:
  address: 0.0.0.0
  port: 8000